services:
  rusty-jeopardy:
    build: .
    ports:
      - "10001:10001"
    restart: always
    volumes:
      - games:/games
networks:
  default:
    name: otel
    external: true

volumes:
  games:
    external: true
